### PR TITLE
Android: Add support for System theme

### PR DESCRIPTION
**Pull request by ua741**
## Description
This is just a fallback for user who ask for this option till we finalize UI for tri-state option.

### CODE REVIEW

**Comment by mnvr** [comment]
Let me think, maybe we just fix this in one go.

**Comment by ua741** [comment]
> Let me think, maybe we just fix this in one go.

Okay :). This is just so that we don't ask the user to uninstall and re-install. We can save brain cycle for now and think about this when we decide to redesign/improve settings screen.

**Comment by mnvr** [comment]
Got it, you're right, I'll just try to do something quick

**Review by ashilkn — APPROVED** [review]

**Comment by ashilkn** [comment]
The "Theme" heading on light theme has very low contrast with the background, other than that everything lgtm
temp

**Review by ashilkn — APPROVED** [review]

**Pull request merged**
