### PR TITLE
Ensure sentry is not enabled for fdroid client

### PR DESCRIPTION
**Pull request by ua741**

### CODE REVIEW

**Review by mnvr — APPROVED** [review]

**Comment by licaon-kter** [comment]
I've build a6681a2fc8181f2ce45fed6662e0518480187df7 and it still connects to `sentry-reporter.ente.io` fyi

**Comment by licaon-kter** [comment]
Fyi, Netguard is on F-Droid ;)

**Comment by ua741** [comment]
> Nope, I've build the F-Droid recipe at [a6681a2](https://github.com/ente-io/frame/commit/a6681a2fc8181f2ce45fed6662e0518480187df7)
> 
> Netguard has PER APP connection logs so you can selectively see which app does what ;)

Unfortunately, we were not able to reproduce it. If possible, please share a screenshot with some details about the request which was being made.

That said, we have pushed a [new version](https://github.com/ente-io/frame/tree/fdroid-0.6.12). This has more safegaurd checks to ensure that sentry is not configured for f-droid version. In this version, we have also removed the reference for `sentry-reporter.ente.io`.

**Comment by licaon-kter** [comment]
No versionName update https://github.com/ente-io/frame/blob/fdroid-0.6.12/pubspec.yaml#L14

But anyway, 1da9410e8a5a7554eeca0877bf563d0e66ae4c8b is still connecting
index

**Comment by licaon-kter** [comment]
_It's always DNS_

Looking again, it appears that Netguard shows the domain names that it knows, and since `api.`, `sentry.`, and `ente.io` share the same IPs it was showing me the first entry that it had cached.

So yes, this appears fixed.

There's also the fact Terms and Privacy policies connect to `sal.ente.io` which is actually `external.simpleanalytics.com` but that's not a direct issue.

**Pull request merged**
